name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '* 8 8 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push php pecl
        uses: docker/build-push-action@v2
        with:
          context: php-pecl
          push: true
          tags: litan1106/php-pecl:latest
      -
        name: Build and push php
        uses: docker/build-push-action@v2
        with:
          context: php
          push: true
          tags: litan1106/php:latest
      -
        name: Build and push go-supervisord
        uses: docker/build-push-action@v2
        with:
          context: golang-supervisord
          push: true
          tags: litan1106/golang-supervisord:latest
      -
        name: Build and push go-mailhog
        uses: docker/build-push-action@v2
        with:
          context: mailhog
          push: true
          tags: litan1106/mailhog:latest
      -
        name: Build and push node-websocket
        uses: docker/build-push-action@v2
        with:
          context: websocket
          push: true
          tags: litan1106/websocket:latest
