name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: php-devcontainer
          push: true
          tags: litan1106/php-devcontainer:latest
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: dotnet-core-devcontainer
          push: true
          tags: litan1106/dotnet-core-devcontainer:latest
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: php
          push: true
          tags: litan1106/php:latest
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: golang-supervisord
          push: true
          tags: litan1106/golang-supervisord:latest
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: mailhog
          push: true
          tags: litan1106/mailhog:latest
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: websocket
          push: true
          tags: litan1106/websocket:latest
