name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '* 8 8 * *'
  workflow_dispatch:

jobs:
  build_php:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push php pecl
        uses: docker/build-push-action@v4
        with:
          context: php-pecl
          push: true
          tags: litan1106/php-pecl:latest
      -
        name: Build and push php
        uses: docker/build-push-action@v4
        with:
          context: php
          push: true
          tags: litan1106/php:latest

  build_golang:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push go-supervisord
        uses: docker/build-push-action@v4
        with:
          context: golang-supervisord
          push: true
          tags: litan1106/golang-supervisord:latest

  build_spark:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push spark
        uses: docker/build-push-action@v4
        with:
          context: spark
          push: true
          tags: litan1106/spark:3.5.2-python-3.12

  build_spark4:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push spark
        uses: docker/build-push-action@v4
        with:
          context: spark
          push: true
          tags: litan1106/spark:4.0.0-python-3.12
          build-args: |
            VARIANT=3.12-slim-bookworm
            JAVA_VERSION=21-noble
            SPARK_VERSION=4.0.0-scala2.13-java21-ubuntu
